#!/bin/bash

pwd=$(dirname $0)

osbin=${pwd}/bin
osetc=${pwd}/etc
oscmd="mono OpenSim.exe"

cd $osbin
if [ -r "${osetc}/OpenSim.ini" ]; then
	oscmd="${oscmd} -inifile=${osetc}/OpenSim.ini"
fi
env LANG=C $oscmd

