#!/bin/bash

pwd=$(dirname $0)
name=$(echo ${pwd} | sed -e "s#/##" -e "s#/#.#g")

osbin=${pwd}/bin
osetc=${pwd}/etc
oscmd="env LANG=C mono OpenSim.exe"

cd ${osbin}
if [ -r "${osetc}/OpenSim.ini" ]; then
	oscmd="${oscmd} -inimaster=OpenSimDefaults.ini -inifile=${osetc}/OpenSim.ini"
fi

if [ "$1" = "screen" ]; then
	screen -dmS ${name} ${oscmd}
else
	$oscmd
fi
